# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 21:24
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bootcamps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.PositiveIntegerField(choices=[(1, 'Footer links'), (2, 'Footer midden'), (3, 'Footer rechts'), (10, 'Registratie aanmeldpagina'), (11, 'Registratie bedankt'), (12, 'Registratie email onderwerp'), (13, 'Registratie email inhoud'), (14, 'Registratie activatie bedankt'), (15, 'Registratie activatie mislukt'), (20, 'Inlogpagina'), (21, 'Uitgelogd pagina'), (30, 'Wachtwoord vergeten pagina'), (31, 'Wachtwoord vergeten bedankt'), (32, 'Wachtwoord vergeten nieuw wachtwoord'), (33, 'Wachtwoord vergeten klaar'), (34, 'Algemene Voorwaarden'), (40, 'Nieuwe zorgorganisatie opgeven'), (41, 'Nieuwe sportclub opgeven'), (50, 'Bedankt aanmelden deelnemer')], unique=True)),
                ('content', models.TextField(verbose_name='inhoud')),
            ],
            options={
                'verbose_name': 'Configuratieparameter',
                'ordering': ['parameter'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('title', models.CharField(max_length=255, verbose_name='titel')),
                ('slug', models.SlugField(blank=True, help_text='het gedeelte achter www.socialesportschool.nl', unique=True, verbose_name='URL')),
                ('menu', models.BooleanField(default=True, verbose_name='zichtbaar in het menu')),
                ('image', models.ImageField(blank=True, help_text='Deze afbeelding wordt de banner van deze pagina', upload_to='', verbose_name='afbeelding')),
            ],
            options={
                'verbose_name': 'Pagina',
                'verbose_name_plural': 'Pagina’s',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('visibility', models.PositiveIntegerField(choices=[(1, 'Altijd zichtbaar'), (2, 'Alleen op desktop'), (3, 'Onzichtbaar')], default=1, verbose_name='zichtbaarheid')),
                ('type', models.PositiveIntegerField(choices=[(1, 'Normaal'), (2, 'Agenda smal'), (3, 'Agenda breed'), (4, 'Partners')], default=1, verbose_name='soort sectie')),
                ('color', models.PositiveIntegerField(choices=[(1, 'Wit'), (2, 'Blauw'), (3, 'Blauw-Wit')], default=1, verbose_name='kleur')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='titel')),
                ('contents', ckeditor.fields.RichTextField(blank=True, verbose_name='inhoud')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='afbeelding')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, help_text='Plak hier een YouTube, Vimeo, of SoundCloud link')),
                ('button', models.CharField(blank=True, max_length=255, verbose_name='button')),
                ('hyperlink', models.CharField(blank=True, max_length=255)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='sss.Page', verbose_name='pagina')),
                ('partners_gemeenten', models.ManyToManyField(blank=True, to='bootcamps.Gemeente')),
                ('partners_locatie', models.ManyToManyField(blank=True, to='bootcamps.ZorgLocatie')),
                ('partners_sport', models.ManyToManyField(blank=True, to='bootcamps.Sportschool')),
                ('partners_zorg', models.ManyToManyField(blank=True, to='bootcamps.ZorgOrganisatie')),
            ],
            options={
                'verbose_name': 'sectie',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('image', models.ImageField(upload_to='', verbose_name='afbeelding')),
                ('hyperlink', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Social Media',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Bestand')),
            ],
            options={
                'ordering': ['file'],
            },
        ),
    ]
