# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-13 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Deze afbeelding wordt de banner van deze pagina', upload_to='', verbose_name='afbeelding (mobiel)'),
        ),
        migrations.AlterField(
            model_name='config',
            name='parameter',
            field=models.PositiveIntegerField(choices=[(1, 'Footer links'), (2, 'Footer midden'), (3, 'Footer rechts'), (10, 'Registratie aanmeldpagina'), (11, 'Registratie bedankt'), (12, 'Registratie email onderwerp'), (13, 'Registratie email inhoud'), (14, 'Registratie activatie bedankt'), (15, 'Registratie activatie mislukt'), (20, 'Inlogpagina'), (21, 'Uitgelogd pagina'), (30, 'Wachtwoord vergeten pagina'), (31, 'Wachtwoord vergeten bedankt'), (32, 'Wachtwoord vergeten nieuw wachtwoord'), (33, 'Wachtwoord vergeten klaar'), (34, 'Algemene Voorwaarden'), (40, 'Nieuwe zorglocatie opgeven'), (41, 'Nieuwe sportclub opgeven'), (42, 'Melding over algemene voorwaarden'), (49, 'Infotekst voordat deelnemers zich aanmelden'), (50, 'Bedankt aanmelden deelnemer'), (60, 'Email na aanmelden deelnemer (onderwerp)'), (61, 'Email na aanmelden deelnemer (inhoud)')], unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, help_text='Deze afbeelding wordt de banner van deze pagina', upload_to='', verbose_name='afbeelding (desktop)'),
        ),
        migrations.AlterField(
            model_name='section',
            name='visibility',
            field=models.PositiveIntegerField(choices=[(1, 'Altijd zichtbaar'), (2, 'Niet op smartphone'), (3, 'Onzichtbaar')], default=1, verbose_name='zichtbaarheid'),
        ),
    ]
