# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportschool',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='zorglocatie',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
