# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamps', '0002_auto_20170926_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='omschrijving'),
        ),
        migrations.AddField(
            model_name='price',
            name='description',
            field=models.CharField(blank=True, help_text='Deze omschrijving komt op de factuur', max_length=255, verbose_name='omschrijving'),
        ),
    ]
