# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-20 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamps', '0004_auto_20171013_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcamp',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='verwijderd'),
        ),
    ]
